spring.application.name=webtodo

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/webtodo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:lerd}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration

spring.jackson.time-zone=Asia/Tokyo
